dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install pycodestyle
# command to run tests
script:
  - find . -iname "*.py" -print0 | xargs -0 pycodestyle --max-line-length 120
